### ISSUE TITLE
Loosen Faraday Version Constraint

### ISSUE THREAD

**Issue by forestsword** [yaacov/prometheus_api_client_ruby#12]
Hello,

Any reason why you need such a specific version constraint?

https://github.com/prometheus/prometheus_api_client_ruby/blob/a510b3beae4689974236e4bc4d34a6addb4aa2c0/prometheus-api-client.gemspec#L18

This has caused me to downgrade faraday in my project. A looser constraint like `~> 0.9` would be appreciated.

**Comment by yaacov** [comment]
👍 #13

**Comment by andrewjtait** [comment]
Is it possible to adjust this again to also support Faraday v2, or is there something incompatible that needs to be resolved?

**Comment by yaacov** [comment]
@andrewjtait hi, can you make a pull request ?
