### ISSUE TITLE
Git tag for v0.6.3 is missing

### ISSUE THREAD

**Issue by nekketsuuu** [yaacov/prometheus_api_client_ruby#24]
Thanks for releasing prometheus-api-client gem v0.6.3! However, I noticed that a git tag for v0.6.3 has been not pushed yet to this repository. Would you please push it for a reference?

- https://rubygems.org/gems/prometheus-api-client/versions/0.6.3
- https://github.com/prometheus/prometheus_api_client_ruby/tags

**Comment by yaacov** [comment]
Thank you for noticing that, added the missing tag:
https://github.com/prometheus/prometheus_api_client_ruby/releases/tag/v0.6.3

**Comment by nekketsuuu** [comment]
Thank you! I appreciate your quick response.
